### ISSUE TITLE
Version bump 0.0.3 -> 0.0.4 breaks compatibility.

### ISSUE THREAD

**Issue by pgroudas** [insynchq/flask-googlelogin#1]
Just an fyi, the addition of the credentials keywork arg breaks the application if you have it configured as your doc suggest.  I would suggest updating them to demonstrate accepting that parameter or taking `**kwargs`` if you're going to add more.

``` python
@app.route('/oauth2callback')
@googlelogin.oauth2callback
def create_or_update_user(userinfo, **kwargs):
    ...
```

**Comment by marksteve** [comment]
Updated the docs: https://github.com/marksteve/flask-googlelogin/commit/25934c0b5303deb588b30ba989278c26671c69d5

Didn't really think people used this haha. If you have suggestions don't hesitate to post an issue or pull requests.
